import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import pg from 'pg';
import dotenv from 'dotenv';
dotenv.config();
const {Pool}=pg;
const app=express();
app.set('trust proxy',1);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('localhost')?false:{rejectUnauthorized:false}});
const PORT=Number(process.env.PORT||8080), ADMIN=process.env.ADMIN_SECRET||'', SESSION=process.env.SESSION_SECRET||'';
const ORIGIN=process.env.CORS_ORIGIN||'*';
app.use(cors({origin:ORIGIN==='*'?true:ORIGIN,methods:['GET','POST'],allowedHeaders:['Content-Type','Authorization']}));
app.use(express.json({limit:'16kb'}));
app.disable('x-powered-by');
const json=(res,data,status=200)=>res.status(status).json(data);
const now=()=>new Date();
function hash(s){return crypto.createHash('sha256').update(String(s),'utf8').digest('hex');}
function code(){return 'ZK-'+crypto.randomBytes(6).toString('hex').toUpperCase();}
function signSession(){const ts=Math.floor(Date.now()/1000);const raw=`${ts}.${crypto.createHmac('sha256',SESSION).update(String(ts)).digest('hex')}`;return Buffer.from(raw).toString('base64url');}
function validSession(req){try{const raw=Buffer.from((req.headers.authorization||'').replace(/^Bearer\s+/i,''),'base64url').toString('utf8');const [ts,sig]=raw.split('.');if(!ts||!sig||!SESSION)return false;if(Math.abs(Math.floor(Date.now()/1000)-Number(ts))>12*60*60)return false;const expected=crypto.createHmac('sha256',SESSION).update(ts).digest('hex');return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected));}catch{return false;}}
function admin(req,res,next){if(!validSession(req))return json(res,{ok:false,error:'unauthorized'},401);next();}
async function rate(key,limit,windowMs){const client=await pool.connect();try{await client.query('BEGIN');const q=await client.query('SELECT window_start,count FROM rate_limits WHERE key=$1 FOR UPDATE',[key]);const n=now();if(!q.rowCount){await client.query('INSERT INTO rate_limits(key,window_start,count) VALUES($1,$2,1)',[key,n]);await client.query('COMMIT');return true;}const row=q.rows[0];const start=new Date(row.window_start);if(n-start>=windowMs){await client.query('UPDATE rate_limits SET window_start=$2,count=1 WHERE key=$1',[key,n]);await client.query('COMMIT');return true;}if(row.count>=limit){await client.query('COMMIT');return false;}await client.query('UPDATE rate_limits SET count=count+1 WHERE key=$1',[key]);await client.query('COMMIT');return true;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
app.get('/api/health',(req,res)=>json(res,{ok:true,service:'zokii-studio-v5',server_time:now().toISOString()}));
app.post('/api/license/activate',async(req,res)=>{try{const ip=req.ip||'unknown';if(!(await rate('activate:'+ip,10,10*60*1000)))return json(res,{valid:false,error:'rate_limited',server_time:now().getTime()},429);const c=String(req.body?.code||'').trim().toUpperCase();const d=String(req.body?.device_id||'').trim();if(!/^ZK-[A-Z0-9]{12}$/.test(c)||!d)return json(res,{valid:false,error:'invalid_code',server_time:now().getTime()},400);const client=await pool.connect();try{await client.query('BEGIN');const q=await client.query('SELECT * FROM licenses WHERE code_hash=$1 FOR UPDATE',[hash(c)]);if(!q.rowCount){await client.query('ROLLBACK');return json(res,{valid:false,error:'invalid_code',server_time:Date.now()},404);}let x=q.rows[0];if(x.status==='revoked'){await client.query('ROLLBACK');return json(res,{valid:false,error:'revoked',server_time:Date.now()},403);}if(x.device_id&&x.device_id!==d){await client.query('ROLLBACK');return json(res,{valid:false,error:'device_bound',server_time:Date.now()},403);}const t=now();if(x.expires_at&&new Date(x.expires_at)<=t){await client.query('UPDATE licenses SET status=\'expired\',updated_at=NOW() WHERE id=$1',[x.id]);await client.query('COMMIT');return json(res,{valid:false,error:'expired',server_time:t.getTime(),expires_at:new Date(x.expires_at).getTime()},403);}if(!x.activated_at){const exp=new Date(t.getTime()+3*24*60*60*1000);await client.query('UPDATE licenses SET status=\'active\',activated_at=NOW(),expires_at=$2,device_id=$3,updated_at=NOW() WHERE id=$1',[x.id,exp,d]);x.expires_at=exp;}await client.query('COMMIT');return json(res,{valid:true,expires_at:new Date(x.expires_at).getTime(),server_time:t.getTime()});}finally{client.release();}}catch(e){console.error(e);return json(res,{valid:false,error:'server_unavailable',server_time:Date.now()},503);}});
app.post('/api/license/verify',async(req,res)=>{try{const ip=req.ip||'unknown';if(!(await rate('verify:'+ip,30,10*60*1000)))return json(res,{valid:false,error:'rate_limited',server_time:Date.now()},429);const c=String(req.body?.code||'').trim().toUpperCase();const h=String(req.body?.code_hash||'').trim().toLowerCase();const d=String(req.body?.device_id||'').trim();if(!d||(!/^ZK-[A-Z0-9]{12}$/.test(c)&&!/^[a-f0-9]{64}$/.test(h)))return json(res,{valid:false,error:'invalid_code',server_time:Date.now()},400);const q=await pool.query(`SELECT * FROM licenses WHERE code_hash=$1`,[h||hash(c)]);if(!q.rowCount)return json(res,{valid:false,error:'invalid_code',server_time:Date.now()},404);const x=q.rows[0],t=now();if(x.status==='revoked')return json(res,{valid:false,error:'revoked',server_time:t.getTime()});if(x.device_id&&x.device_id!==d)return json(res,{valid:false,error:'device_bound',server_time:t.getTime()});if(!x.expires_at||new Date(x.expires_at)<=t){await pool.query('UPDATE licenses SET status=\'expired\',updated_at=NOW() WHERE id=$1',[x.id]);return json(res,{valid:false,error:'expired',server_time:t.getTime(),expires_at:x.expires_at?new Date(x.expires_at).getTime():0});}return json(res,{valid:true,expires_at:new Date(x.expires_at).getTime(),server_time:t.getTime()});}catch(e){console.error(e);return json(res,{valid:false,error:'server_unavailable',server_time:Date.now()},503);}});
app.post('/api/admin/login',async(req,res)=>{try{const ip=req.ip||'unknown';if(!(await rate('login:'+ip,5,15*60*1000)))return json(res,{ok:false,error:'login_failed'},429);const supplied=String(req.body?.password||'');if(!ADMIN||!supplied||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(ADMIN)))return json(res,{ok:false,error:'login_failed'},401);return json(res,{ok:true,token:signSession()});}catch{return json(res,{ok:false,error:'login_failed'},401);}});
app.get('/api/admin/licenses',admin,async(req,res)=>{try{const q=await pool.query('SELECT code,status,created_at,activated_at,expires_at,device_id FROM licenses ORDER BY created_at DESC');return json(res,{ok:true,licenses:q.rows});}catch{return json(res,{ok:false,error:'server_error'},500);}});
app.post('/api/admin/licenses/create',admin,async(req,res)=>{try{let c=code();while((await pool.query('SELECT 1 FROM licenses WHERE code=$1',[c])).rowCount)c=code();const q=await pool.query('INSERT INTO licenses(code,code_hash,status) VALUES($1,$2,\'unused\') RETURNING code,status,created_at,expires_at,device_id',[c,hash(c)]);return json(res,{ok:true,license:q.rows[0]});}catch{return json(res,{ok:false,error:'server_error'},500);}});
async function change(req,res,kind){const c=String(req.body?.code||'').trim().toUpperCase();if(!/^ZK-[A-Z0-9]{12}$/.test(c))return json(res,{ok:false,error:'not_found'},404);const q=await pool.query('SELECT * FROM licenses WHERE code=$1',[c]);if(!q.rowCount)return json(res,{ok:false,error:'not_found'},404);const x=q.rows[0];if(kind==='revoke')await pool.query('UPDATE licenses SET status=\'revoked\',updated_at=NOW() WHERE id=$1',[x.id]);if(kind==='delete')await pool.query('DELETE FROM licenses WHERE id=$1',[x.id]);if(kind==='reset')await pool.query('UPDATE licenses SET device_id=NULL,updated_at=NOW() WHERE id=$1',[x.id]);if(kind==='extend'){const days=Math.min(30,Math.max(1,Number(req.body?.days||3)));const base=x.expires_at&&new Date(x.expires_at)>now()?new Date(x.expires_at):now();const exp=new Date(base.getTime()+days*86400000);await pool.query('UPDATE licenses SET expires_at=$2,status=\'active\',updated_at=NOW() WHERE id=$1',[x.id,exp]);}const out=await pool.query('SELECT code,status,created_at,activated_at,expires_at,device_id FROM licenses WHERE id=$1',[x.id]);return json(res,{ok:true,license:out.rowCount?out.rows[0]:null});}
app.post('/api/admin/licenses/revoke',admin,(req,res)=>change(req,res,'revoke'));app.post('/api/admin/licenses/delete',admin,(req,res)=>change(req,res,'delete'));app.post('/api/admin/licenses/reset-device',admin,(req,res)=>change(req,res,'reset'));app.post('/api/admin/licenses/extend',admin,(req,res)=>change(req,res,'extend'));
app.use((err,req,res,next)=>{console.error(err);json(res,{ok:false,error:'server_error'},500);});
app.listen(PORT,()=>console.log(`Zokii Studio v5 API listening on ${PORT}`));
