const API_BASE=(window.ZOKII_API_URL||'https://YOUR-API-DOMAIN.example.com').replace(/\/$/,'');let token=localStorage.getItem('zokii_admin_token')||'';let licenses=[];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function req(path,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{},token?{Authorization:'Bearer '+token}:{});const r=await fetch(API_BASE+path,opt);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'request_failed');return j}
function fmt(x){return x?new Date(x).toLocaleString(): '—'}function render(){let q=$('search').value.toLowerCase();let a=licenses.filter(x=>(x.code+' '+(x.device_id||'')).toLowerCase().includes(q));$('active').textContent=licenses.filter(x=>x.status==='active').length;$('expired').textContent=licenses.filter(x=>x.status==='expired').length;$('total').textContent=licenses.length;$('rows').innerHTML=a.map(x=>`<tr><td><b>${esc(x.code)}</b></td><td><span class="pill">${esc(x.status.toUpperCase())}</span></td><td>${fmt(x.created_at)}</td><td>${fmt(x.expires_at)}</td><td>${esc(x.device_id||'UNBOUND')}</td><td><button class="btn dark" onclick="copyCode('${esc(x.code)}')">COPY</button> <button class="btn dark" onclick="action('reset-device','${esc(x.code)}')">RESET</button> <button class="btn dark" onclick="action('extend','${esc(x.code)}')">EXTEND</button> <button class="btn dark" onclick="action('revoke','${esc(x.code)}')">REVOKE</button> <button class="btn dark" onclick="action('delete','${esc(x.code)}')">DELETE</button></td></tr>`).join('')}
async function load(){try{const j=await req('/api/admin/licenses');licenses=j.licenses||[];render();$('login').classList.add('hidden');$('dash').classList.remove('hidden')}catch(e){localStorage.removeItem('zokii_admin_token');token='';$('loginMsg').textContent='Session expired or server unavailable.';$('dash').classList.add('hidden');$('login').classList.remove('hidden')}}
$('loginBtn').onclick=async()=>{try{const j=await req('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('password').value})});token=j.token;localStorage.setItem('zokii_admin_token',token);$('loginMsg').textContent='';load()}catch(e){$('loginMsg').textContent='Login failed.'}};
$('generate').onclick=async()=>{try{const j=await req('/api/admin/licenses/create',{method:'POST',body:'{}'});const x=j.license;$('result').textContent=`Generated: ${x.code} • Created: ${fmt(x.created_at)} • 3 days start on first activation.`;await load()}catch(e){$('result').textContent='Could not generate license.'}};
$('refresh').onclick=load;$('logout').onclick=()=>{localStorage.removeItem('zokii_admin_token');location.reload()};$('search').oninput=render;
window.copyCode=async c=>{await navigator.clipboard.writeText(c);$('result').textContent='Copied: '+c};window.action=async(kind,code)=>{let body={code};if(kind==='extend'){const d=prompt('Extend by days','3');if(!d)return;body.days=Number(d)}try{await req('/api/admin/licenses/'+kind,{method:'POST',body:JSON.stringify(body)});await load()}catch(e){$('result').textContent='Action failed.'}};
if(token)load();
